[2022-10-09T23:00:14.566+0000] {processor.py:156} INFO - Started process (PID=17415) to work on /opt/airflow/dags/desafioAirflow/desafio-indicium.py
[2022-10-09T23:00:14.566+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/desafioAirflow/desafio-indicium.py for tasks to queue
[2022-10-09T23:00:14.567+0000] {logging_mixin.py:117} INFO - [2022-10-09T23:00:14.567+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/desafioAirflow/desafio-indicium.py
[2022-10-09T23:00:14.921+0000] {logging_mixin.py:117} INFO - [2022-10-09T23:00:14.919+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/desafioAirflow/desafio-indicium.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/desafioAirflow/desafio-indicium.py", line 4, in <module>
    from dags.desafioAirflow.teste import leitura
ModuleNotFoundError: No module named 'dags'
[2022-10-09T23:00:14.921+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/desafioAirflow/desafio-indicium.py
[2022-10-09T23:00:14.948+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/desafioAirflow/desafio-indicium.py took 0.388 seconds
[2022-10-09T23:00:45.140+0000] {processor.py:156} INFO - Started process (PID=17480) to work on /opt/airflow/dags/desafioAirflow/desafio-indicium.py
[2022-10-09T23:00:45.147+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/desafioAirflow/desafio-indicium.py for tasks to queue
[2022-10-09T23:00:45.147+0000] {logging_mixin.py:117} INFO - [2022-10-09T23:00:45.147+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/desafioAirflow/desafio-indicium.py
[2022-10-09T23:00:45.402+0000] {logging_mixin.py:117} INFO - [2022-10-09T23:00:45.401+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/desafioAirflow/desafio-indicium.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/desafioAirflow/desafio-indicium.py", line 4, in <module>
    from dags.desafioAirflow.teste import leitura
ModuleNotFoundError: No module named 'dags'
[2022-10-09T23:00:45.402+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/desafioAirflow/desafio-indicium.py
[2022-10-09T23:00:45.426+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/desafioAirflow/desafio-indicium.py took 0.293 seconds
[2022-10-09T23:00:48.170+0000] {processor.py:156} INFO - Started process (PID=17482) to work on /opt/airflow/dags/desafioAirflow/desafio-indicium.py
[2022-10-09T23:00:48.171+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/desafioAirflow/desafio-indicium.py for tasks to queue
[2022-10-09T23:00:48.172+0000] {logging_mixin.py:117} INFO - [2022-10-09T23:00:48.172+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/desafioAirflow/desafio-indicium.py
[2022-10-09T23:00:48.430+0000] {logging_mixin.py:117} INFO - [2022-10-09T23:00:48.429+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/desafioAirflow/desafio-indicium.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/desafioAirflow/desafio-indicium.py", line 29, in <module>
    task1 = PythonOperator(
NameError: name 'PythonOperator' is not defined
[2022-10-09T23:00:48.430+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/desafioAirflow/desafio-indicium.py
[2022-10-09T23:00:48.462+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/desafioAirflow/desafio-indicium.py took 0.298 seconds
[2022-10-09T23:00:50.337+0000] {processor.py:156} INFO - Started process (PID=17490) to work on /opt/airflow/dags/desafioAirflow/desafio-indicium.py
[2022-10-09T23:00:50.339+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/desafioAirflow/desafio-indicium.py for tasks to queue
[2022-10-09T23:00:50.340+0000] {logging_mixin.py:117} INFO - [2022-10-09T23:00:50.340+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/desafioAirflow/desafio-indicium.py
[2022-10-09T23:00:50.675+0000] {logging_mixin.py:117} INFO - [2022-10-09T23:00:50.674+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/desafioAirflow/desafio-indicium.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/desafioAirflow/desafio-indicium.py", line 29, in <module>
    task1 = PythonOperator(
NameError: name 'PythonOperator' is not defined
[2022-10-09T23:00:50.676+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/desafioAirflow/desafio-indicium.py
[2022-10-09T23:00:50.704+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/desafioAirflow/desafio-indicium.py took 0.375 seconds
[2022-10-09T23:01:20.833+0000] {processor.py:156} INFO - Started process (PID=17555) to work on /opt/airflow/dags/desafioAirflow/desafio-indicium.py
[2022-10-09T23:01:20.834+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/desafioAirflow/desafio-indicium.py for tasks to queue
[2022-10-09T23:01:20.835+0000] {logging_mixin.py:117} INFO - [2022-10-09T23:01:20.835+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/desafioAirflow/desafio-indicium.py
[2022-10-09T23:01:21.151+0000] {logging_mixin.py:117} INFO - [2022-10-09T23:01:21.150+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/desafioAirflow/desafio-indicium.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/desafioAirflow/desafio-indicium.py", line 29, in <module>
    task1 = PythonOperator(
NameError: name 'PythonOperator' is not defined
[2022-10-09T23:01:21.152+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/desafioAirflow/desafio-indicium.py
[2022-10-09T23:01:21.180+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/desafioAirflow/desafio-indicium.py took 0.354 seconds
[2022-10-09T23:01:51.295+0000] {processor.py:156} INFO - Started process (PID=17618) to work on /opt/airflow/dags/desafioAirflow/desafio-indicium.py
[2022-10-09T23:01:51.296+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/desafioAirflow/desafio-indicium.py for tasks to queue
[2022-10-09T23:01:51.297+0000] {logging_mixin.py:117} INFO - [2022-10-09T23:01:51.297+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/desafioAirflow/desafio-indicium.py
[2022-10-09T23:01:51.600+0000] {logging_mixin.py:117} INFO - [2022-10-09T23:01:51.600+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/desafioAirflow/desafio-indicium.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/desafioAirflow/desafio-indicium.py", line 29, in <module>
    task1 = PythonOperator(
NameError: name 'PythonOperator' is not defined
[2022-10-09T23:01:51.601+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/desafioAirflow/desafio-indicium.py
[2022-10-09T23:01:51.627+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/desafioAirflow/desafio-indicium.py took 0.337 seconds
[2022-10-09T23:02:22.316+0000] {processor.py:156} INFO - Started process (PID=17676) to work on /opt/airflow/dags/desafioAirflow/desafio-indicium.py
[2022-10-09T23:02:22.323+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/desafioAirflow/desafio-indicium.py for tasks to queue
[2022-10-09T23:02:22.324+0000] {logging_mixin.py:117} INFO - [2022-10-09T23:02:22.323+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/desafioAirflow/desafio-indicium.py
[2022-10-09T23:02:22.656+0000] {logging_mixin.py:117} INFO - [2022-10-09T23:02:22.655+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/desafioAirflow/desafio-indicium.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/desafioAirflow/desafio-indicium.py", line 29, in <module>
    task1 = PythonOperator(
NameError: name 'PythonOperator' is not defined
[2022-10-09T23:02:22.657+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/desafioAirflow/desafio-indicium.py
[2022-10-09T23:02:22.689+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/desafioAirflow/desafio-indicium.py took 0.379 seconds
[2022-10-09T23:02:52.920+0000] {processor.py:156} INFO - Started process (PID=17741) to work on /opt/airflow/dags/desafioAirflow/desafio-indicium.py
[2022-10-09T23:02:52.921+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/desafioAirflow/desafio-indicium.py for tasks to queue
[2022-10-09T23:02:52.923+0000] {logging_mixin.py:117} INFO - [2022-10-09T23:02:52.923+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/desafioAirflow/desafio-indicium.py
[2022-10-09T23:02:53.277+0000] {logging_mixin.py:117} INFO - [2022-10-09T23:02:53.275+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/desafioAirflow/desafio-indicium.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/desafioAirflow/desafio-indicium.py", line 29, in <module>
    task1 = PythonOperator(
NameError: name 'PythonOperator' is not defined
[2022-10-09T23:02:53.277+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/desafioAirflow/desafio-indicium.py
[2022-10-09T23:02:53.312+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/desafioAirflow/desafio-indicium.py took 0.396 seconds
[2022-10-09T23:03:23.417+0000] {processor.py:156} INFO - Started process (PID=17799) to work on /opt/airflow/dags/desafioAirflow/desafio-indicium.py
[2022-10-09T23:03:23.419+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/desafioAirflow/desafio-indicium.py for tasks to queue
[2022-10-09T23:03:23.422+0000] {logging_mixin.py:117} INFO - [2022-10-09T23:03:23.421+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/desafioAirflow/desafio-indicium.py
[2022-10-09T23:03:23.761+0000] {logging_mixin.py:117} INFO - [2022-10-09T23:03:23.760+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/desafioAirflow/desafio-indicium.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/desafioAirflow/desafio-indicium.py", line 29, in <module>
    task1 = PythonOperator(
NameError: name 'PythonOperator' is not defined
[2022-10-09T23:03:23.761+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/desafioAirflow/desafio-indicium.py
[2022-10-09T23:03:23.786+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/desafioAirflow/desafio-indicium.py took 0.373 seconds
[2022-10-09T23:03:53.886+0000] {processor.py:156} INFO - Started process (PID=17864) to work on /opt/airflow/dags/desafioAirflow/desafio-indicium.py
[2022-10-09T23:03:53.887+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/desafioAirflow/desafio-indicium.py for tasks to queue
[2022-10-09T23:03:53.887+0000] {logging_mixin.py:117} INFO - [2022-10-09T23:03:53.887+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/desafioAirflow/desafio-indicium.py
[2022-10-09T23:03:54.198+0000] {logging_mixin.py:117} INFO - [2022-10-09T23:03:54.197+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/desafioAirflow/desafio-indicium.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/desafioAirflow/desafio-indicium.py", line 29, in <module>
    task1 = PythonOperator(
NameError: name 'PythonOperator' is not defined
[2022-10-09T23:03:54.198+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/desafioAirflow/desafio-indicium.py
[2022-10-09T23:03:54.221+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/desafioAirflow/desafio-indicium.py took 0.340 seconds
[2022-10-09T23:04:24.309+0000] {processor.py:156} INFO - Started process (PID=17920) to work on /opt/airflow/dags/desafioAirflow/desafio-indicium.py
[2022-10-09T23:04:24.310+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/desafioAirflow/desafio-indicium.py for tasks to queue
[2022-10-09T23:04:24.311+0000] {logging_mixin.py:117} INFO - [2022-10-09T23:04:24.311+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/desafioAirflow/desafio-indicium.py
[2022-10-09T23:04:24.611+0000] {logging_mixin.py:117} INFO - [2022-10-09T23:04:24.610+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/desafioAirflow/desafio-indicium.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/desafioAirflow/desafio-indicium.py", line 29, in <module>
    task1 = PythonOperator(
NameError: name 'PythonOperator' is not defined
[2022-10-09T23:04:24.611+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/desafioAirflow/desafio-indicium.py
[2022-10-09T23:04:24.642+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/desafioAirflow/desafio-indicium.py took 0.338 seconds
[2022-10-09T23:04:55.510+0000] {processor.py:156} INFO - Started process (PID=17985) to work on /opt/airflow/dags/desafioAirflow/desafio-indicium.py
[2022-10-09T23:04:55.511+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/desafioAirflow/desafio-indicium.py for tasks to queue
[2022-10-09T23:04:55.512+0000] {logging_mixin.py:117} INFO - [2022-10-09T23:04:55.511+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/desafioAirflow/desafio-indicium.py
[2022-10-09T23:04:55.799+0000] {logging_mixin.py:117} INFO - [2022-10-09T23:04:55.798+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/desafioAirflow/desafio-indicium.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/desafioAirflow/desafio-indicium.py", line 29, in <module>
    task1 = PythonOperator(
NameError: name 'PythonOperator' is not defined
[2022-10-09T23:04:55.800+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/desafioAirflow/desafio-indicium.py
[2022-10-09T23:04:55.828+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/desafioAirflow/desafio-indicium.py took 0.323 seconds
[2022-10-09T23:05:26.532+0000] {processor.py:156} INFO - Started process (PID=18050) to work on /opt/airflow/dags/desafioAirflow/desafio-indicium.py
[2022-10-09T23:05:26.534+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/desafioAirflow/desafio-indicium.py for tasks to queue
[2022-10-09T23:05:26.535+0000] {logging_mixin.py:117} INFO - [2022-10-09T23:05:26.534+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/desafioAirflow/desafio-indicium.py
[2022-10-09T23:05:26.827+0000] {logging_mixin.py:117} INFO - [2022-10-09T23:05:26.826+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/desafioAirflow/desafio-indicium.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/desafioAirflow/desafio-indicium.py", line 29, in <module>
    task1 = PythonOperator(
NameError: name 'PythonOperator' is not defined
[2022-10-09T23:05:26.828+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/desafioAirflow/desafio-indicium.py
[2022-10-09T23:05:26.849+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/desafioAirflow/desafio-indicium.py took 0.322 seconds
[2022-10-09T23:05:57.735+0000] {processor.py:156} INFO - Started process (PID=18106) to work on /opt/airflow/dags/desafioAirflow/desafio-indicium.py
[2022-10-09T23:05:57.737+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/desafioAirflow/desafio-indicium.py for tasks to queue
[2022-10-09T23:05:57.738+0000] {logging_mixin.py:117} INFO - [2022-10-09T23:05:57.737+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/desafioAirflow/desafio-indicium.py
[2022-10-09T23:05:58.058+0000] {logging_mixin.py:117} INFO - [2022-10-09T23:05:58.057+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/desafioAirflow/desafio-indicium.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/desafioAirflow/desafio-indicium.py", line 29, in <module>
    task1 = PythonOperator(
NameError: name 'PythonOperator' is not defined
[2022-10-09T23:05:58.059+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/desafioAirflow/desafio-indicium.py
[2022-10-09T23:05:58.087+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/desafioAirflow/desafio-indicium.py took 0.356 seconds
[2022-10-09T23:06:27.140+0000] {processor.py:156} INFO - Started process (PID=18172) to work on /opt/airflow/dags/desafioAirflow/desafio-indicium.py
[2022-10-09T23:06:27.141+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/desafioAirflow/desafio-indicium.py for tasks to queue
[2022-10-09T23:06:27.142+0000] {logging_mixin.py:117} INFO - [2022-10-09T23:06:27.141+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/desafioAirflow/desafio-indicium.py
[2022-10-09T23:06:27.491+0000] {processor.py:768} INFO - DAG(s) dict_keys(['desafio-indicium']) retrieved from /opt/airflow/dags/desafioAirflow/desafio-indicium.py
[2022-10-09T23:06:27.811+0000] {logging_mixin.py:117} INFO - [2022-10-09T23:06:27.811+0000] {manager.py:507} INFO - Created Permission View: can read on DAG:desafio-indicium
[2022-10-09T23:06:27.833+0000] {logging_mixin.py:117} INFO - [2022-10-09T23:06:27.833+0000] {manager.py:507} INFO - Created Permission View: can delete on DAG:desafio-indicium
[2022-10-09T23:06:27.848+0000] {logging_mixin.py:117} INFO - [2022-10-09T23:06:27.848+0000] {manager.py:507} INFO - Created Permission View: can edit on DAG:desafio-indicium
[2022-10-09T23:06:27.849+0000] {logging_mixin.py:117} INFO - [2022-10-09T23:06:27.849+0000] {dag.py:2573} INFO - Sync 1 DAGs
[2022-10-09T23:06:28.017+0000] {logging_mixin.py:117} INFO - [2022-10-09T23:06:28.017+0000] {dag.py:2594} INFO - Creating ORM DAG for desafio-indicium
[2022-10-09T23:06:28.040+0000] {logging_mixin.py:117} INFO - [2022-10-09T23:06:28.039+0000] {dag.py:3328} INFO - Setting next_dagrun for desafio-indicium to 2022-07-13T00:00:00+00:00, run_after=2022-07-14T00:00:00+00:00
[2022-10-09T23:06:28.065+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/desafioAirflow/desafio-indicium.py took 0.929 seconds
[2022-10-09T23:06:58.823+0000] {processor.py:156} INFO - Started process (PID=18235) to work on /opt/airflow/dags/desafioAirflow/desafio-indicium.py
[2022-10-09T23:06:58.829+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/desafioAirflow/desafio-indicium.py for tasks to queue
[2022-10-09T23:06:58.830+0000] {logging_mixin.py:117} INFO - [2022-10-09T23:06:58.830+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/desafioAirflow/desafio-indicium.py
[2022-10-09T23:06:59.552+0000] {processor.py:768} INFO - DAG(s) dict_keys(['desafio-indicium']) retrieved from /opt/airflow/dags/desafioAirflow/desafio-indicium.py
[2022-10-09T23:06:59.636+0000] {logging_mixin.py:117} INFO - [2022-10-09T23:06:59.636+0000] {dag.py:2573} INFO - Sync 1 DAGs
[2022-10-09T23:06:59.711+0000] {logging_mixin.py:117} INFO - [2022-10-09T23:06:59.708+0000] {dag.py:3328} INFO - Setting next_dagrun for desafio-indicium to 2022-08-15T00:00:00+00:00, run_after=2022-08-16T00:00:00+00:00
[2022-10-09T23:06:59.761+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/desafioAirflow/desafio-indicium.py took 0.947 seconds
[2022-10-09T23:07:29.928+0000] {processor.py:156} INFO - Started process (PID=18296) to work on /opt/airflow/dags/desafioAirflow/desafio-indicium.py
[2022-10-09T23:07:29.929+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/desafioAirflow/desafio-indicium.py for tasks to queue
[2022-10-09T23:07:29.930+0000] {logging_mixin.py:117} INFO - [2022-10-09T23:07:29.930+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/desafioAirflow/desafio-indicium.py
[2022-10-09T23:07:30.522+0000] {processor.py:768} INFO - DAG(s) dict_keys(['desafio-indicium']) retrieved from /opt/airflow/dags/desafioAirflow/desafio-indicium.py
[2022-10-09T23:07:30.619+0000] {logging_mixin.py:117} INFO - [2022-10-09T23:07:30.618+0000] {dag.py:2573} INFO - Sync 1 DAGs
[2022-10-09T23:07:30.691+0000] {logging_mixin.py:117} INFO - [2022-10-09T23:07:30.691+0000] {dag.py:3328} INFO - Setting next_dagrun for desafio-indicium to 2022-09-23T00:00:00+00:00, run_after=2022-09-24T00:00:00+00:00
[2022-10-09T23:07:30.742+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/desafioAirflow/desafio-indicium.py took 0.826 seconds
[2022-10-09T23:08:01.131+0000] {processor.py:156} INFO - Started process (PID=18352) to work on /opt/airflow/dags/desafioAirflow/desafio-indicium.py
[2022-10-09T23:08:01.132+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/desafioAirflow/desafio-indicium.py for tasks to queue
[2022-10-09T23:08:01.133+0000] {logging_mixin.py:117} INFO - [2022-10-09T23:08:01.133+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/desafioAirflow/desafio-indicium.py
[2022-10-09T23:08:01.551+0000] {processor.py:768} INFO - DAG(s) dict_keys(['desafio-indicium']) retrieved from /opt/airflow/dags/desafioAirflow/desafio-indicium.py
[2022-10-09T23:08:01.621+0000] {logging_mixin.py:117} INFO - [2022-10-09T23:08:01.620+0000] {dag.py:2573} INFO - Sync 1 DAGs
[2022-10-09T23:08:01.677+0000] {logging_mixin.py:117} INFO - [2022-10-09T23:08:01.676+0000] {dag.py:3328} INFO - Setting next_dagrun for desafio-indicium to 2022-10-09T00:00:00+00:00, run_after=2022-10-10T00:00:00+00:00
[2022-10-09T23:08:01.709+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/desafioAirflow/desafio-indicium.py took 0.584 seconds
[2022-10-09T23:08:31.972+0000] {processor.py:156} INFO - Started process (PID=18418) to work on /opt/airflow/dags/desafioAirflow/desafio-indicium.py
[2022-10-09T23:08:31.973+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/desafioAirflow/desafio-indicium.py for tasks to queue
[2022-10-09T23:08:31.974+0000] {logging_mixin.py:117} INFO - [2022-10-09T23:08:31.974+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/desafioAirflow/desafio-indicium.py
[2022-10-09T23:08:32.316+0000] {processor.py:768} INFO - DAG(s) dict_keys(['desafio-indicium']) retrieved from /opt/airflow/dags/desafioAirflow/desafio-indicium.py
[2022-10-09T23:08:32.364+0000] {logging_mixin.py:117} INFO - [2022-10-09T23:08:32.363+0000] {dag.py:2573} INFO - Sync 1 DAGs
[2022-10-09T23:08:32.412+0000] {logging_mixin.py:117} INFO - [2022-10-09T23:08:32.411+0000] {dag.py:3328} INFO - Setting next_dagrun for desafio-indicium to 2022-10-09T00:00:00+00:00, run_after=2022-10-10T00:00:00+00:00
[2022-10-09T23:08:32.448+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/desafioAirflow/desafio-indicium.py took 0.478 seconds
[2022-10-09T23:09:02.767+0000] {processor.py:156} INFO - Started process (PID=18485) to work on /opt/airflow/dags/desafioAirflow/desafio-indicium.py
[2022-10-09T23:09:02.768+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/desafioAirflow/desafio-indicium.py for tasks to queue
[2022-10-09T23:09:02.769+0000] {logging_mixin.py:117} INFO - [2022-10-09T23:09:02.769+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/desafioAirflow/desafio-indicium.py
[2022-10-09T23:09:03.193+0000] {processor.py:768} INFO - DAG(s) dict_keys(['desafio-indicium']) retrieved from /opt/airflow/dags/desafioAirflow/desafio-indicium.py
[2022-10-09T23:09:03.256+0000] {logging_mixin.py:117} INFO - [2022-10-09T23:09:03.256+0000] {dag.py:2573} INFO - Sync 1 DAGs
[2022-10-09T23:09:03.318+0000] {logging_mixin.py:117} INFO - [2022-10-09T23:09:03.318+0000] {dag.py:3328} INFO - Setting next_dagrun for desafio-indicium to 2022-10-09T00:00:00+00:00, run_after=2022-10-10T00:00:00+00:00
[2022-10-09T23:09:03.351+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/desafioAirflow/desafio-indicium.py took 0.592 seconds
[2022-10-09T23:09:33.590+0000] {processor.py:156} INFO - Started process (PID=18541) to work on /opt/airflow/dags/desafioAirflow/desafio-indicium.py
[2022-10-09T23:09:33.591+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/desafioAirflow/desafio-indicium.py for tasks to queue
[2022-10-09T23:09:33.592+0000] {logging_mixin.py:117} INFO - [2022-10-09T23:09:33.592+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/desafioAirflow/desafio-indicium.py
[2022-10-09T23:09:34.012+0000] {processor.py:768} INFO - DAG(s) dict_keys(['desafio-indicium']) retrieved from /opt/airflow/dags/desafioAirflow/desafio-indicium.py
[2022-10-09T23:09:34.072+0000] {logging_mixin.py:117} INFO - [2022-10-09T23:09:34.072+0000] {dag.py:2573} INFO - Sync 1 DAGs
[2022-10-09T23:09:34.115+0000] {logging_mixin.py:117} INFO - [2022-10-09T23:09:34.114+0000] {dag.py:3328} INFO - Setting next_dagrun for desafio-indicium to 2022-10-09T00:00:00+00:00, run_after=2022-10-10T00:00:00+00:00
[2022-10-09T23:09:34.145+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/desafioAirflow/desafio-indicium.py took 0.559 seconds
[2022-10-09T23:10:04.407+0000] {processor.py:156} INFO - Started process (PID=18607) to work on /opt/airflow/dags/desafioAirflow/desafio-indicium.py
[2022-10-09T23:10:04.408+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/desafioAirflow/desafio-indicium.py for tasks to queue
[2022-10-09T23:10:04.409+0000] {logging_mixin.py:117} INFO - [2022-10-09T23:10:04.409+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/desafioAirflow/desafio-indicium.py
[2022-10-09T23:10:04.740+0000] {processor.py:768} INFO - DAG(s) dict_keys(['desafio-indicium']) retrieved from /opt/airflow/dags/desafioAirflow/desafio-indicium.py
[2022-10-09T23:10:04.796+0000] {logging_mixin.py:117} INFO - [2022-10-09T23:10:04.795+0000] {dag.py:2573} INFO - Sync 1 DAGs
[2022-10-09T23:10:04.852+0000] {logging_mixin.py:117} INFO - [2022-10-09T23:10:04.852+0000] {dag.py:3328} INFO - Setting next_dagrun for desafio-indicium to 2022-10-09T00:00:00+00:00, run_after=2022-10-10T00:00:00+00:00
[2022-10-09T23:10:04.884+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/desafioAirflow/desafio-indicium.py took 0.483 seconds
[2022-10-09T23:10:35.694+0000] {processor.py:156} INFO - Started process (PID=18663) to work on /opt/airflow/dags/desafioAirflow/desafio-indicium.py
[2022-10-09T23:10:35.701+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/desafioAirflow/desafio-indicium.py for tasks to queue
[2022-10-09T23:10:35.703+0000] {logging_mixin.py:117} INFO - [2022-10-09T23:10:35.702+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/desafioAirflow/desafio-indicium.py
[2022-10-09T23:10:36.003+0000] {processor.py:768} INFO - DAG(s) dict_keys(['desafio-indicium']) retrieved from /opt/airflow/dags/desafioAirflow/desafio-indicium.py
[2022-10-09T23:10:36.054+0000] {logging_mixin.py:117} INFO - [2022-10-09T23:10:36.053+0000] {dag.py:2573} INFO - Sync 1 DAGs
[2022-10-09T23:10:36.090+0000] {logging_mixin.py:117} INFO - [2022-10-09T23:10:36.090+0000] {dag.py:3328} INFO - Setting next_dagrun for desafio-indicium to 2022-10-09T00:00:00+00:00, run_after=2022-10-10T00:00:00+00:00
[2022-10-09T23:10:36.117+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/desafioAirflow/desafio-indicium.py took 0.427 seconds
[2022-10-09T23:11:06.170+0000] {processor.py:156} INFO - Started process (PID=18728) to work on /opt/airflow/dags/desafioAirflow/desafio-indicium.py
[2022-10-09T23:11:06.171+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/desafioAirflow/desafio-indicium.py for tasks to queue
[2022-10-09T23:11:06.173+0000] {logging_mixin.py:117} INFO - [2022-10-09T23:11:06.172+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/desafioAirflow/desafio-indicium.py
[2022-10-09T23:11:06.549+0000] {processor.py:768} INFO - DAG(s) dict_keys(['desafio-indicium']) retrieved from /opt/airflow/dags/desafioAirflow/desafio-indicium.py
[2022-10-09T23:11:06.593+0000] {logging_mixin.py:117} INFO - [2022-10-09T23:11:06.592+0000] {dag.py:2573} INFO - Sync 1 DAGs
[2022-10-09T23:11:06.640+0000] {logging_mixin.py:117} INFO - [2022-10-09T23:11:06.640+0000] {dag.py:3328} INFO - Setting next_dagrun for desafio-indicium to 2022-10-09T00:00:00+00:00, run_after=2022-10-10T00:00:00+00:00
[2022-10-09T23:11:06.674+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/desafioAirflow/desafio-indicium.py took 0.511 seconds
[2022-10-09T23:11:36.863+0000] {processor.py:156} INFO - Started process (PID=18793) to work on /opt/airflow/dags/desafioAirflow/desafio-indicium.py
[2022-10-09T23:11:36.870+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/desafioAirflow/desafio-indicium.py for tasks to queue
[2022-10-09T23:11:36.871+0000] {logging_mixin.py:117} INFO - [2022-10-09T23:11:36.871+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/desafioAirflow/desafio-indicium.py
[2022-10-09T23:11:37.217+0000] {processor.py:768} INFO - DAG(s) dict_keys(['desafio-indicium']) retrieved from /opt/airflow/dags/desafioAirflow/desafio-indicium.py
[2022-10-09T23:11:37.272+0000] {logging_mixin.py:117} INFO - [2022-10-09T23:11:37.271+0000] {dag.py:2573} INFO - Sync 1 DAGs
[2022-10-09T23:11:37.317+0000] {logging_mixin.py:117} INFO - [2022-10-09T23:11:37.317+0000] {dag.py:3328} INFO - Setting next_dagrun for desafio-indicium to 2022-10-09T00:00:00+00:00, run_after=2022-10-10T00:00:00+00:00
[2022-10-09T23:11:37.347+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/desafioAirflow/desafio-indicium.py took 0.491 seconds
[2022-10-09T23:12:07.561+0000] {processor.py:156} INFO - Started process (PID=18851) to work on /opt/airflow/dags/desafioAirflow/desafio-indicium.py
[2022-10-09T23:12:07.562+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/desafioAirflow/desafio-indicium.py for tasks to queue
[2022-10-09T23:12:07.562+0000] {logging_mixin.py:117} INFO - [2022-10-09T23:12:07.562+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/desafioAirflow/desafio-indicium.py
[2022-10-09T23:12:07.893+0000] {processor.py:768} INFO - DAG(s) dict_keys(['desafio-indicium']) retrieved from /opt/airflow/dags/desafioAirflow/desafio-indicium.py
[2022-10-09T23:12:07.951+0000] {logging_mixin.py:117} INFO - [2022-10-09T23:12:07.951+0000] {dag.py:2573} INFO - Sync 1 DAGs
[2022-10-09T23:12:07.999+0000] {logging_mixin.py:117} INFO - [2022-10-09T23:12:07.998+0000] {dag.py:3328} INFO - Setting next_dagrun for desafio-indicium to 2022-10-09T00:00:00+00:00, run_after=2022-10-10T00:00:00+00:00
[2022-10-09T23:12:08.031+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/desafioAirflow/desafio-indicium.py took 0.473 seconds
